---
- block:
    - name: install
      pacman:
        name: radvd
    - name: configure
      template:
        src: radvd.conf.j2
        dest: /etc/radvd.conf
        mode: "0644"
    - name: enable
      service:
        name: radvd
        enabled: yes
  tags:
    - service
    - radvd
