---
- hosts:
    - all
  gather_facts: yes
  remote_user: ansible
  become: yes
  roles:
    - role: system/user
    - role: system/host
    - role: system/vconsole
    - role: system/timezone
    - role: system/locale
    - role: system/makepkg
    - role: system/package
    - role: system/sysctl/forwarding

    - role: service/networkd/local_router
    - role: service/dhcpcd
    - role: service/dhcpd
    - role: service/sshd
    - role: smarthome

