---
- block:
    - name: configure
      template:
        src: "{{ item }}.j2"
        dest: "/etc/sysctl.d/{{ item }}"
        mode: "0644"
      with_items:
        - 10-enable-forwarding.conf
  tags:
    - system
    - sysctl