ipv4:
  address: 192.168.100.1
  networkaddress: 192.168.100.0
  subnetmask: 255.255.255.0
  prefix: 24

ipv6:
  uniquelocaladdress: fd00::1
  prefix: 64

interface:
  bridge: br0
  lan: eth0
  wan: enp1s0u1
  ip6tunnel: ip6tun

dnscrypt:
  port: 15353
  servers:
    - cloudflare
    - cloudflare-family-ipv6
    - google
    - google-ipv6

dnsmasq:
  dhcp:
    range: "192.168.100.200, 192.168.100.240, 12h"
