---
- block:
    - name: install
      pacman:
        name: dnscrypt-proxy
    - name: configure
      template:
        src: "{{ item }}.j2"
        dest: "/etc/dnscrypt-proxy/{{ item }}"
        mode: "0644"
      with_items:
        - dnscrypt-proxy.toml
        - forwarding-rules.txt
    - name: enable
      service:
        name: dnscrypt-proxy.service
        enabled: yes
  tags:
    - service
    - dnscrypt_proxy
