---
- block:
    - name: make working dir
      file:
        path: /home/ansible/work/ndppd
        state: directory
        mode: "0755"
      become: yes
      become_user: ansible
    - name: fetch repository
      git:
        repo: "https://github.com/DanielAdolfsson/ndppd.git"
        dest: "/home/ansible/work/ndppd"
        version: "{{ ndppd.branch }}"
      become: yes
      become_user: ansible
      register: fetch_ndppd
    - block:
        - name: make all
          make:
            chdir: /home/ansible/work/ndppd
            target: all
          become: yes
          become_user: ansible
        - name: Populate service facts
          service_facts:
        - name: stop service
          service:
            name: httpd
            state: stopped
          when: "'ndppd' in services"
        - name: make install
          make:
            chdir: /home/ansible/work/ndppd
            target: install
      when: fetch_ndppd.changed
    - name: copy service
      copy:
        src: ndppd.service
        dest: "/usr/lib/systemd/system/ndppd.service"
        mode: "0644"
    - name: configure
      template:
        src: ndppd.conf.j2
        dest: "/etc/ndppd.conf"
        mode: "0644"
    - name: enable
      service:
        name: ndppd.service
        enabled: yes
  tags:
    - service
    - ndppd
